# Generated by Django 3.1 on 2020-08-18 20:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vehicles', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vehicle',
            old_name='data',
            new_name='info',
        ),
    ]
