# Generated by Django 3.1 on 2020-08-16 23:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Vehicle',
        ),
    ]
