# Generated by Django 3.1 on 2020-08-26 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_apikey'),
    ]

    operations = [
        migrations.AddField(
            model_name='apikey',
            name='daily_limit',
            field=models.IntegerField(default=5000),
        ),
    ]
